### ISSUE TITLE
Test against timezone aware datetimes

### ISSUE THREAD

**Issue by kipe** [kipe/pycron#2]
Need to test also against timezone aware datetimes, as they're quite popular, especially in Django.

**Comment by jacobtomlinson** [comment]
I've found that it works well with [arrow in opsdroid](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/parsers/crontab.py#L24). But explicit unit tests would be good.

**Comment by kipe** [comment]
Closed via #6
