### ISSUE TITLE
* * * * * always returns true

### ISSUE THREAD

**Issue by olivierdalang** [kipe/pycron#21]
Hi !

It seems the pattern `* * * * *` always returns true, even if the condition isn't met. See following example :

```
import pycron
from datetime import datetime as dt

d1 = dt(2020,1,1,hour=12,minute=0, second=3)
d2 = dt(2020,1,1,hour=12,minute=0, second=4)

pycron.has_been("* * * * *", d1, d2)
# expecting False, but we get True
```

This means we get multiple executions per minute if we check more than once a minute...

**Comment by kipe** [comment]
Well, if you want, feel free to make a pull request rectifying the situation.

This isn't meant as a timing daemon anyways, just as a simple library to check if timestamp matches a cron syntax string. If you need an actual scheduler, either you need to implement it yourself or look into using something like [crontabs](https://github.com/robdmc/crontabs) or [Celery](http://www.celeryproject.org).
