### ISSUE TITLE
Behavior for day checking is incorrect

### ISSUE THREAD

**Issue by kenahoo** [kipe/pycron#29]
The docs for `crontab` (https://man7.org/linux/man-pages/man5/crontab.5.html) say this:

> Commands are executed by [cron(8)](https://man7.org/linux/man-pages/man8/cron.8.html) when the 'minute', 'hour', and 'month of the year' fields match the current time, _and_ at least one of the two 'day' fields ('day of month', or 'day of week') match the current time (see "Note" below).

and here's the Note:

> Note: The day of a command's execution can be specified in the following two fields — 'day of month', and 'day of week'.  If both fields are restricted (i.e., do not contain the "*" character), the command will be run when either field matches the current time.  For example, "30 4 1,15 * 5" would cause a command to be run at 4:30 am on the 1st and 15th of each month, plus every Friday.

However, the `pycron` functionality is different - it requires that *both* the fields match:

```
>>> import pycron
>>> from datetime import datetime
>>> dt = datetime(2022, 6, 23)  # A Thursday
>>> pycron.is_now('* * 22 * thu', dt)
False
>>> pycron.is_now('* * 23 * thu', dt)
True
>>> pycron.is_now('* * 23 * fri', dt)
False
```

**Comment by adamsxs** [comment]
@kenahoo you could use https://github.com/kiorky/croniter?tab=readme-ov-file#testing-if-a-date-matches-a-crontab in the mean time
