### ISSUE TITLE
Make names case insensitive

### ISSUE THREAD

**Issue by adamsxs** [kipe/pycron#31]
Hey thanks for open-sourcing this. Almost ended up using it for a project at work and while we did side-step the issue still stumbled on something I'm happy to add if the repo's still maintained.

To reproduce on version 3.0.0:
```
import datetime
pycron.is_now("0 0 19 * thu", datetime.datetime(2024, 9, 19, 0, 0))
# True
pycron.is_now("0 0 19 * Thu", datetime.datetime(2024, 9, 19, 0, 0))
# False
```
From what I can find in docs for cron and in some browser based expression generators it should be case-insenstive.
https://en.wikipedia.org/wiki/Cron
https://man7.org/linux/man-pages/man5/crontab.5.html

**Comment by kipe** [comment]
Thanks, this is now fixed :+1:
